version: '3.4'

services:
  taggingsystem:
    image: taggingsystem
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./core
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./core/.env
    volumes:
      - ./core:/app
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  worker:
    build: ./core
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - taggingsystem
      - redis
      - db
    env_file:
      - ./core/.env

  celery-beat:
    build: ./core
    container_name: beat
    command: celery -A core beat -l info
    volumes:
      - ./core:/app
    depends_on:
      - taggingsystem
      - redis
      - db
    env_file:
      - ./core/.env


  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
volumes:
  postgres_data: